// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// Type definitions for working with Minecraft Bedrock Edition pack JSON schemas.
// Project: https://learn.microsoft.com/minecraft/creator/

/**
 * @packageDocumentation
 * Contains types for working with various Minecraft Bedrock Edition JSON schemas.
 * 
 * Items Documentation - minecraft:use_modifiers
 * 
 * minecraft:use_modifiers Samples

Apple - https://github.com/Mojang/bedrock-samples/tree/preview/behavior_pack/items/apple.json

"minecraft:use_modifiers": {
  "use_duration": 1.6,
  "movement_modifier": 0.35
}


Copper Spear - https://github.com/Mojang/bedrock-samples/tree/preview/behavior_pack/items/copper_spear.json

"minecraft:use_modifiers": {
  "use_duration": 72000,
  "emit_vibrations": false,
  "start_sound": "item.spear.use",
  "movement_modifier": 1
}


Wooden Spear - https://github.com/Mojang/bedrock-samples/tree/preview/behavior_pack/items/wooden_spear.json

"minecraft:use_modifiers": {
  "use_duration": 72000,
  "emit_vibrations": false,
  "start_sound": "item.wooden_spear.use",
  "movement_modifier": 1
}


Cooked Dream Turkey - https://github.com/microsoft/minecraft-samples/tree/main/casual_creator/chill_dreams/1_dream_turkey/behavior_packs/mamm_cds/items/cooked_dream_turkey.json

"minecraft:use_modifiers": {
  "use_duration": 4,
  "movement_modifier": 0.35
}


My Sword Shoot - https://github.com/microsoft/minecraft-samples/tree/main/custom_items/behavior_packs/custom_item/items/my_sword_shoot.json

"minecraft:use_modifiers": {
  "use_duration": 3
}


Elixir - https://github.com/microsoft/minecraft-samples/tree/main/starter_items/behavior_packs/starter_Items/items/elixir.json

"minecraft:use_modifiers": {
  "use_duration": 4
}


Hard Biscuit - https://github.com/microsoft/minecraft-samples/tree/main/starter_items/behavior_packs/starter_Items/items/hard_biscuit.json

"minecraft:use_modifiers": {
  "use_duration": 3,
  "movement_modifier": 0.35
}

 */

import * as jsoncommon from './../../../jsoncommon';

/**
 * Item Use Modifiers (minecraft:use_modifiers)
 * Modifies use behavior, including how long the item takes to use
 * and the player's movement speed.
 */
export default interface MinecraftUseModifiers {

  /**
   * @remarks
   * Whether vibrations are emitted when the item starts or stops being
   * used.
   */
  emit_vibrations?: boolean;

  /**
   * @remarks
   * Multiplier applied to the player's movement speed while the item
   * is in use.
   * 
   * Sample Values:
   * Apple: 0.35
   *
   * Copper Spear: 1
   *
   *
   *
   */
  movement_modifier?: number;

  /**
   * @remarks
   * Sound played when the item starts being used.
   * 
   * Sample Values:
   * Copper Spear: "item.spear.use"
   *
   *
   * Wooden Spear: "item.wooden_spear.use"
   *
   */
  start_sound?: string;

  /**
   * @remarks
   * Time, in seconds, that the item takes to use.
   * 
   * Sample Values:
   * Apple: 1.6
   *
   * Copper Spear: 72000
   *
   *
   * Cooked Dream Turkey: 4
   *
   */
  use_duration?: number;

}


export enum MinecraftUseModifiersStartSound {
  activate = `activate`,
  addChest = `add.chest`,
  admire = `admire`,
  agitated = `agitated`,
  ambient = `ambient`,
  ambientAggressive = `ambient.aggressive`,
  ambientBaby = `ambient.baby`,
  ambientBasaltDeltasAdditions = `ambient.basalt_deltas.additions`,
  ambientBasaltDeltasLoop = `ambient.basalt_deltas.loop`,
  ambientBasaltDeltasMood = `ambient.basalt_deltas.mood`,
  ambientCandle = `ambient.candle`,
  ambientCave = `ambient.cave`,
  ambientCrimsonForestAdditions = `ambient.crimson_forest.additions`,
  ambientCrimsonForestLoop = `ambient.crimson_forest.loop`,
  ambientCrimsonForestMood = `ambient.crimson_forest.mood`,
  ambientInAir = `ambient.in.air`,
  ambientInRaid = `ambient.in.raid`,
  ambientInWater = `ambient.in.water`,
  ambientNetherWastesAdditions = `ambient.nether_wastes.additions`,
  ambientNetherWastesLoop = `ambient.nether_wastes.loop`,
  ambientNetherWastesMood = `ambient.nether_wastes.mood`,
  ambientPollinate = `ambient.pollinate`,
  ambientScreamer = `ambient.screamer`,
  ambientSoulsandValleyAdditions = `ambient.soulsand_valley.additions`,
  ambientSoulsandValleyLoop = `ambient.soulsand_valley.loop`,
  ambientSoulsandValleyMood = `ambient.soulsand_valley.mood`,
  ambientTame = `ambient.tame`,
  ambientUnderwaterEnter = `ambient.underwater.enter`,
  ambientUnderwaterExit = `ambient.underwater.exit`,
  ambientWarpedForestAdditions = `ambient.warped_forest.additions`,
  ambientWarpedForestLoop = `ambient.warped_forest.loop`,
  ambientWarpedForestMood = `ambient.warped_forest.mood`,
  ambientWeatherTheEndLightFlash = `ambient.weather.the_end_light_flash`,
  ambientWorried = `ambient.worried`,
  angry = `angry`,
  applyEffectBadOmen = `apply_effect.bad_omen`,
  applyEffectRaidOmen = `apply_effect.raid_omen`,
  applyEffectTrialOmen = `apply_effect.trial_omen`,
  armor = `armor`,
  armorBreakWolf = `armor.break_wolf`,
  armorCrackWolf = `armor.crack_wolf`,
  armorEquipChain = `armor.equip_chain`,
  armorEquipCopper = `armor.equip_copper`,
  armorEquipDiamond = `armor.equip_diamond`,
  armorEquipElytra = `armor.equip_elytra`,
  armorEquipGeneric = `armor.equip_generic`,
  armorEquipGold = `armor.equip_gold`,
  armorEquipIron = `armor.equip_iron`,
  armorEquipLeather = `armor.equip_leather`,
  armorEquipNetherite = `armor.equip_netherite`,
  armorEquipWolf = `armor.equip_wolf`,
  armorRepairWolf = `armor.repair_wolf`,
  armorUnequipGeneric = `armor.unequip_generic`,
  armorUnequipWolf = `armor.unequip_wolf`,
  attach = `attach`,
  attack = `attack`,
  attackCritical = `attack.critical`,
  attackNodamage = `attack.nodamage`,
  attackStrong = `attack.strong`,
  balloonpop = `balloonpop`,
  beaconActivate = `beacon.activate`,
  beaconAmbient = `beacon.ambient`,
  beaconDeactivate = `beacon.deactivate`,
  beaconPower = `beacon.power`,
  blast = `blast`,
  blockBambooSaplingPlace = `block.bamboo_sapling.place`,
  blockBarrelClose = `block.barrel.close`,
  blockBarrelOpen = `block.barrel.open`,
  blockBeehiveDrip = `block.beehive.drip`,
  blockBeehiveEnter = `block.beehive.enter`,
  blockBeehiveExit = `block.beehive.exit`,
  blockBeehiveShear = `block.beehive.shear`,
  blockBeehiveWork = `block.beehive.work`,
  blockBellHit = `block.bell.hit`,
  blockBlastfurnaceFireCrackle = `block.blastfurnace.fire_crackle`,
  blockCampfireCrackle = `block.campfire.crackle`,
  blockCartographyTableUse = `block.cartography_table.use`,
  blockClick = `block.click`,
  blockClickFail = `block.click.fail`,
  blockComposterEmpty = `block.composter.empty`,
  blockComposterFill = `block.composter.fill`,
  blockComposterFillSuccess = `block.composter.fill_success`,
  blockComposterReady = `block.composter.ready`,
  blockCopperBulbTurnOff = `block.copper_bulb.turn_off`,
  blockCopperBulbTurnOn = `block.copper_bulb.turn_on`,
  blockCreakingHeartTrail = `block.creaking_heart.trail`,
  blockDecoratedPotInsert = `block.decorated_pot.insert`,
  blockDecoratedPotInsertFail = `block.decorated_pot.insert_fail`,
  blockEnchantingTableUse = `block.enchanting_table.use`,
  blockEndPortalSpawn = `block.end_portal.spawn`,
  blockEndPortalFrameFill = `block.end_portal_frame.fill`,
  blockFletchingTableUse = `block.fletching_table.use`,
  blockFrogSpawnBreak = `block.frog_spawn.break`,
  blockFrogSpawnHatch = `block.frog_spawn.hatch`,
  blockFurnaceLit = `block.furnace.lit`,
  blockGrindstoneUse = `block.grindstone.use`,
  blockLoomUse = `block.loom.use`,
  blockScaffoldingClimb = `block.scaffolding.climb`,
  blockSculkSpread = `block.sculk.spread`,
  blockSculkCatalystBloom = `block.sculk_catalyst.bloom`,
  blockSculkSensorPlace = `block.sculk_sensor.place`,
  blockSculkShriekerPlace = `block.sculk_shrieker.place`,
  blockSculkShriekerShriek = `block.sculk_shrieker.shriek`,
  blockSignWaxedInteractFail = `block.sign.waxed_interact_fail`,
  blockSmithingTableUse = `block.smithing_table.use`,
  blockSmokerSmoke = `block.smoker.smoke`,
  blockSnifferEggCrack = `block.sniffer_egg.crack`,
  blockSnifferEggHatch = `block.sniffer_egg.hatch`,
  blockStonecutterUse = `block.stonecutter.use`,
  blockSweetBerryBushHurt = `block.sweet_berry_bush.hurt`,
  blockSweetBerryBushPick = `block.sweet_berry_bush.pick`,
  blockTurtleEggAttack = `block.turtle_egg.attack`,
  blockTurtleEggBreak = `block.turtle_egg.break`,
  blockTurtleEggCrack = `block.turtle_egg.crack`,
  blockTurtleEggHatch = `block.turtle_egg.hatch`,
  boost = `boost`,
  born = `born`,
  bottleDragonbreath = `bottle.dragonbreath`,
  bottleEmpty = `bottle.empty`,
  bottleFill = `bottle.fill`,
  bow = `bow`,
  bowHit = `bow.hit`,
  break = `break`,
  breakBlock = `break.block`,
  breakPot = `break_pot`,
  breathe = `breathe`,
  breezeWindChargeBurst = `breeze_wind_charge.burst`,
  brush = `brush`,
  brushCompleted = `brush_completed`,
  bubbleDown = `bubble.down`,
  bubbleDowninside = `bubble.downinside`,
  bubblePop = `bubble.pop`,
  bubbleUp = `bubble.up`,
  bubbleUpinside = `bubble.upinside`,
  bucketEmptyFish = `bucket.empty.fish`,
  bucketEmptyLava = `bucket.empty.lava`,
  bucketEmptyPowderSnow = `bucket.empty.powder_snow`,
  bucketEmptyWater = `bucket.empty.water`,
  bucketFillFish = `bucket.fill.fish`,
  bucketFillLava = `bucket.fill.lava`,
  bucketFillPowderSnow = `bucket.fill.powder_snow`,
  bucketFillWater = `bucket.fill.water`,
  bulletHit = `bullet.hit`,
  bundleDropContents = `bundle.drop_contents`,
  bundleInsert = `bundle.insert`,
  bundleInsertFail = `bundle.insert_fail`,
  bundleRemoveOne = `bundle.remove_one`,
  burp = `burp`,
  buttonClickOff = `button.click_off`,
  buttonClickOn = `button.click_on`,
  cakeAddCandle = `cake.add_candle`,
  cameraTakePicture = `camera.take_picture`,
  cantBreed = `cant_breed`,
  castSpell = `cast.spell`,
  cauldronDripLavaPointedDripstone = `cauldron_drip.lava.pointed_dripstone`,
  cauldronDripWaterPointedDripstone = `cauldron_drip.water.pointed_dripstone`,
  celebrate = `celebrate`,
  charge = `charge`,
  chargeSculk = `charge.sculk`,
  chestClosed = `chest.closed`,
  chestOpen = `chest.open`,
  chimeAmethystBlock = `chime.amethyst_block`,
  chorusdeath = `chorusdeath`,
  chorusgrow = `chorusgrow`,
  close = `close`,
  closeLong = `close_long`,
  conduitActivate = `conduit.activate`,
  conduitAmbient = `conduit.ambient`,
  conduitAttack = `conduit.attack`,
  conduitDeactivate = `conduit.deactivate`,
  conduitShort = `conduit.short`,
  convertMooshroom = `convert_mooshroom`,
  convertToDrowned = `convert_to_drowned`,
  convertToFrog = `convert_to_frog`,
  convertToStray = `convert_to_stray`,
  convertedToZombified = `converted_to_zombified`,
  copperWaxOff = `copper.wax.off`,
  copperWaxOn = `copper.wax.on`,
  crafterCraft = `crafter.craft`,
  crafterDisableSlot = `crafter.disable_slot`,
  crafterFail = `crafter.fail`,
  creakingHeartSpawn = `creaking_heart_spawn`,
  crossbowLoadingEnd = `crossbow.loading.end`,
  crossbowLoadingMiddle = `crossbow.loading.middle`,
  crossbowLoadingStart = `crossbow.loading.start`,
  crossbowQuickChargeEnd = `crossbow.quick_charge.end`,
  crossbowQuickChargeMiddle = `crossbow.quick_charge.middle`,
  crossbowQuickChargeStart = `crossbow.quick_charge.start`,
  crossbowShoot = `crossbow.shoot`,
  dashReady = `dash_ready`,
  deactivate = `deactivate`,
  death = `death`,
  deathBaby = `death.baby`,
  deathInWater = `death.in.water`,
  deathMidVolume = `death.mid.volume`,
  deathMinVolume = `death.min.volume`,
  deathScreamer = `death.screamer`,
  deathToZombie = `death.to.zombie`,
  default = `default`,
  deny = `deny`,
  detach = `detach`,
  disappeared = `disappeared`,
  doorClose = `door.close`,
  doorOpen = `door.open`,
  drink = `drink`,
  drinkHoney = `drink.honey`,
  drinkMilk = `drink.milk`,
  dripLavaPointedDripstone = `drip.lava.pointed_dripstone`,
  dripWaterPointedDripstone = `drip.water.pointed_dripstone`,
  dropSlot = `drop.slot`,
  eat = `eat`,
  elderguardianCurse = `elderguardian.curse`,
  elemconstructOpen = `elemconstruct.open`,
  enderchestClosed = `enderchest.closed`,
  enderchestOpen = `enderchest.open`,
  explode = `explode`,
  extinguishCandle = `extinguish.candle`,
  extinguishFire = `extinguish.fire`,
  fall = `fall`,
  fallBig = `fall.big`,
  fallSmall = `fall.small`,
  fang = `fang`,
  fenceGateClose = `fence_gate.close`,
  fenceGateOpen = `fence_gate.open`,
  fire = `fire`,
  fizz = `fizz`,
  flap = `flap`,
  flop = `flop`,
  fly = `fly`,
  freeze = `freeze`,
  fuse = `fuse`,
  gallop = `gallop`,
  glass = `glass`,
  glowSquidInkSquirt = `glow_squid.ink_squirt`,
  glowstickUse = `glowstick.use`,
  growl = `growl`,
  haggle = `haggle`,
  haggleIdle = `haggle.idle`,
  haggleNo = `haggle.no`,
  haggleYes = `haggle.yes`,
  heartbeat = `heartbeat`,
  heavyStep = `heavy.step`,
  hit = `hit`,
  hornBreak = `horn_break`,
  hornCall0 = `horn_call0`,
  hornCall1 = `horn_call1`,
  hornCall2 = `horn_call2`,
  hornCall3 = `horn_call3`,
  hornCall4 = `horn_call4`,
  hornCall5 = `horn_call5`,
  hornCall6 = `horn_call6`,
  hornCall7 = `horn_call7`,
  hurt = `hurt`,
  hurtBaby = `hurt.baby`,
  hurtInWater = `hurt.in.water`,
  hurtReduced = `hurt.reduced`,
  hurtScreamer = `hurt.screamer`,
  icebombHit = `icebomb.hit`,
  ignite = `ignite`,
  imitateBlaze = `imitate.blaze`,
  imitateBogged = `imitate.bogged`,
  imitateBreeze = `imitate.breeze`,
  imitateCamelHusk = `imitate.camel_husk`,
  imitateCaveSpider = `imitate.cave_spider`,
  imitateCreaking = `imitate.creaking`,
  imitateCreeper = `imitate.creeper`,
  imitateDrowned = `imitate.drowned`,
  imitateElderGuardian = `imitate.elder_guardian`,
  imitateEnderDragon = `imitate.ender_dragon`,
  imitateEnderman = `imitate.enderman`,
  imitateEndermite = `imitate.endermite`,
  imitateEvocationIllager = `imitate.evocation_illager`,
  imitateGhast = `imitate.ghast`,
  imitateGuardian = `imitate.guardian`,
  imitateHappyGhast = `imitate.happy_ghast`,
  imitateHusk = `imitate.husk`,
  imitateMagmaCube = `imitate.magma_cube`,
  imitateParched = `imitate.parched`,
  imitatePhantom = `imitate.phantom`,
  imitatePillager = `imitate.pillager`,
  imitatePolarBear = `imitate.polar_bear`,
  imitateRavager = `imitate.ravager`,
  imitateShulker = `imitate.shulker`,
  imitateSilverfish = `imitate.silverfish`,
  imitateSkeleton = `imitate.skeleton`,
  imitateSlime = `imitate.slime`,
  imitateSpider = `imitate.spider`,
  imitateStray = `imitate.stray`,
  imitateVex = `imitate.vex`,
  imitateVindicationIllager = `imitate.vindication_illager`,
  imitateWarden = `imitate.warden`,
  imitateWitch = `imitate.witch`,
  imitateWither = `imitate.wither`,
  imitateWitherSkeleton = `imitate.wither_skeleton`,
  imitateWolf = `imitate.wolf`,
  imitateZoglin = `imitate.zoglin`,
  imitateZombie = `imitate.zombie`,
  imitateZombiePigman = `imitate.zombie_pigman`,
  imitateZombieVillager = `imitate.zombie_villager`,
  insert = `insert`,
  insertEnchanted = `insert_enchanted`,
  irongolemCrack = `irongolem.crack`,
  irongolemRepair = `irongolem.repair`,
  itemBookPut = `item.book.put`,
  itemEnchantLunge1 = `item.enchant.lunge1`,
  itemEnchantLunge2 = `item.enchant.lunge2`,
  itemEnchantLunge3 = `item.enchant.lunge3`,
  itemFizz = `item.fizz`,
  itemShieldBlock = `item.shield.block`,
  itemSpearAttackHit = `item.spear.attack_hit`,
  itemSpearAttackMiss = `item.spear.attack_miss`,
  itemSpearUse = `item.spear.use`,
  itemSpyglassStopUsing = `item.spyglass.stop_using`,
  itemSpyglassUse = `item.spyglass.use`,
  itemTridentHit = `item.trident.hit`,
  itemTridentHitGround = `item.trident.hit_ground`,
  itemTridentReturn = `item.trident.return`,
  itemTridentRiptide1 = `item.trident.riptide_1`,
  itemTridentRiptide2 = `item.trident.riptide_2`,
  itemTridentRiptide3 = `item.trident.riptide_3`,
  itemTridentThrow = `item.trident.throw`,
  itemTridentThunder = `item.trident.thunder`,
  itemUseOn = `item.use.on`,
  itemWoodenSpearAttackHit = `item.wooden_spear.attack_hit`,
  itemWoodenSpearAttackMiss = `item.wooden_spear.attack_miss`,
  itemWoodenSpearUse = `item.wooden_spear.use`,
  itemGiven = `item_given`,
  itemTaken = `item_taken`,
  itemThrown = `item_thrown`,
  jump = `jump`,
  jumpPrevent = `jump.prevent`,
  jumpToBlock = `jump_to_block`,
  land = `land`,
  largeBlast = `large.blast`,
  launch = `launch`,
  lava = `lava`,
  lavaPop = `lava.pop`,
  layEgg = `lay_egg`,
  laySpawn = `lay_spawn`,
  leadBreak = `lead.break`,
  leadLeash = `lead.leash`,
  leadUnleash = `lead.unleash`,
  leashknotBreak = `leashknot.break`,
  leashknotPlace = `leashknot.place`,
  levelup = `levelup`,
  listening = `listening`,
  listeningAngry = `listening_angry`,
  lodestoneCompassLinkCompassToLodestone = `lodestone_compass.link_compass_to_lodestone`,
  ltReactionBleach = `lt.reaction.bleach`,
  ltReactionEpaste = `lt.reaction.epaste`,
  ltReactionEpaste2 = `lt.reaction.epaste2`,
  ltReactionFertilizer = `lt.reaction.fertilizer`,
  ltReactionFire = `lt.reaction.fire`,
  ltReactionFireball = `lt.reaction.fireball`,
  ltReactionIcebomb = `lt.reaction.icebomb`,
  ltReactionMgsalt = `lt.reaction.mgsalt`,
  ltReactionMiscexplosion = `lt.reaction.miscexplosion`,
  ltReactionMiscfire = `lt.reaction.miscfire`,
  ltReactionMiscmystical = `lt.reaction.miscmystical`,
  ltReactionMiscmystical2 = `lt.reaction.miscmystical2`,
  ltReactionProduct = `lt.reaction.product`,
  maceHeavySmashGround = `mace.heavy_smash_ground`,
  maceSmashAir = `mace.smash_air`,
  maceSmashGround = `mace.smash_ground`,
  mad = `mad`,
  milk = `milk`,
  milkScreamer = `milk.screamer`,
  milkSuspiciously = `milk_suspiciously`,
  mobArmadilloBrush = `mob.armadillo.brush`,
  mobArmadilloScuteDrop = `mob.armadillo.scute_drop`,
  mobArmorStandPlace = `mob.armor_stand.place`,
  mobHoglinConvertedToZombified = `mob.hoglin.converted_to_zombified`,
  mobHuskConvertToZombie = `mob.husk.convert_to_zombie`,
  mobPigDeath = `mob.pig.death`,
  mobPlayerHurtDrown = `mob.player.hurt_drown`,
  mobPlayerHurtFreeze = `mob.player.hurt_freeze`,
  mobPlayerHurtOnFire = `mob.player.hurt_on_fire`,
  mobWarning = `mob.warning`,
  mobWarningBaby = `mob.warning.baby`,
  multiSwap = `multi_swap`,
  nearbyClose = `nearby_close`,
  nearbyCloser = `nearby_closer`,
  nearbyClosest = `nearby_closest`,
  note = `note`,
  noteBass = `note.bass`,
  ominousBottleEndUse = `ominous_bottle.end_use`,
  ominousItemSpawnerAboutToSpawnItem = `ominous_item_spawner.about_to_spawn_item`,
  ominousItemSpawnerSpawnItem = `ominous_item_spawner.spawn_item`,
  ominousItemSpawnerSpawnItemBegin = `ominous_item_spawner.spawn_item_begin`,
  open = `open`,
  openLong = `open_long`,
  panic = `panic`,
  pant = `pant`,
  particleSoulEscapeLoud = `particle.soul_escape.loud`,
  particleSoulEscapeQuiet = `particle.soul_escape.quiet`,
  pickBerriesCaveVines = `pick_berries.cave_vines`,
  pickup = `pickup`,
  pickupEnchanted = `pickup_enchanted`,
  pistonIn = `piston.in`,
  pistonOut = `piston.out`,
  place = `place`,
  placeInWater = `place_in_water`,
  placeItem = `place_item`,
  plop = `plop`,
  pop = `pop`,
  portal = `portal`,
  portalTravel = `portal.travel`,
  potionBrewed = `potion.brewed`,
  powerOff = `power.off`,
  powerOffSculkSensor = `power.off.sculk_sensor`,
  powerOn = `power.on`,
  powerOnSculkSensor = `power.on.sculk_sensor`,
  preRam = `pre_ram`,
  preRamScreamer = `pre_ram.screamer`,
  prepareAttack = `prepare.attack`,
  prepareSummon = `prepare.summon`,
  prepareWololo = `prepare.wololo`,
  presneeze = `presneeze`,
  pressurePlateClickOff = `pressure_plate.click_off`,
  pressurePlateClickOn = `pressure_plate.click_on`,
  pumpkinCarve = `pumpkin.carve`,
  purr = `purr`,
  purreow = `purreow`,
  raidHorn = `raid.horn`,
  ramImpact = `ram_impact`,
  ramImpactScreamer = `ram_impact.screamer`,
  randomAnvilUse = `random.anvil_use`,
  reappeared = `reappeared`,
  record11 = `record.11`,
  record13 = `record.13`,
  record5 = `record.5`,
  recordBlocks = `record.blocks`,
  recordCat = `record.cat`,
  recordChirp = `record.chirp`,
  recordCreator = `record.creator`,
  recordCreatorMusicBox = `record.creator_music_box`,
  recordFar = `record.far`,
  recordLavaChicken = `record.lava_chicken`,
  recordMall = `record.mall`,
  recordMellohi = `record.mellohi`,
  recordOtherside = `record.otherside`,
  recordPigstep = `record.pigstep`,
  recordPrecipice = `record.precipice`,
  recordRelic = `record.relic`,
  recordStal = `record.stal`,
  recordStrad = `record.strad`,
  recordTears = `record.tears`,
  recordWait = `record.wait`,
  recordWard = `record.ward`,
  reflect = `reflect`,
  remedy = `remedy`,
  respawnAnchorAmbient = `respawn_anchor.ambient`,
  respawnAnchorCharge = `respawn_anchor.charge`,
  respawnAnchorDeplete = `respawn_anchor.deplete`,
  respawnAnchorSetSpawn = `respawn_anchor.set_spawn`,
  retreat = `retreat`,
  roar = `roar`,
  saddle = `saddle`,
  scared = `scared`,
  scrape = `scrape`,
  screech = `screech`,
  shake = `shake`,
  shatterPot = `shatter_pot`,
  shear = `shear`,
  shoot = `shoot`,
  shulkerClose = `shulker.close`,
  shulkerOpen = `shulker.open`,
  shulkerboxClosed = `shulkerbox.closed`,
  shulkerboxOpen = `shulkerbox.open`,
  singleSwap = `single_swap`,
  sleep = `sleep`,
  smithingTableUse = `smithing_table.use`,
  sneeze = `sneeze`,
  sonicBoom = `sonic_boom`,
  sonicCharge = `sonic_charge`,
  sparklerActive = `sparkler.active`,
  sparklerUse = `sparkler.use`,
  spawn = `spawn`,
  splash = `splash`,
  spongeAbsorb = `sponge.absorb`,
  squidInkSquirt = `squid.ink_squirt`,
  squishBig = `squish.big`,
  squishSmall = `squish.small`,
  stare = `stare`,
  stateChange = `state_change`,
  step = `step`,
  stepBaby = `step.baby`,
  stepLava = `step_lava`,
  stepSand = `step_sand`,
  stun = `stun`,
  swim = `swim`,
  swoop = `swoop`,
  takeoff = `takeoff`,
  teleport = `teleport`,
  tempt = `tempt`,
  thorns = `thorns`,
  throw = `throw`,
  thunder = `thunder`,
  tiltDownBigDripleaf = `tilt_down.big_dripleaf`,
  tiltUpBigDripleaf = `tilt_up.big_dripleaf`,
  tongue = `tongue`,
  trapdoorClose = `trapdoor.close`,
  trapdoorOpen = `trapdoor.open`,
  trialSpawnerAmbient = `trial_spawner.ambient`,
  trialSpawnerAmbientOminous = `trial_spawner.ambient_ominous`,
  trialSpawnerChargeActivate = `trial_spawner.charge_activate`,
  trialSpawnerCloseShutter = `trial_spawner.close_shutter`,
  trialSpawnerDetectPlayer = `trial_spawner.detect_player`,
  trialSpawnerEjectItem = `trial_spawner.eject_item`,
  trialSpawnerOpenShutter = `trial_spawner.open_shutter`,
  trialSpawnerSpawnMob = `trial_spawner.spawn_mob`,
  tripod = `tripod`,
  twinkle = `twinkle`,
  uiCartographyTableTakeResult = `ui.cartography_table.take_result`,
  uiLoomTakeResult = `ui.loom.take_result`,
  uiStonecutterTakeResult = `ui.stonecutter.take_result`,
  undefined = `undefined`,
  unfect = `unfect`,
  unfreeze = `unfreeze`,
  unsaddle = `unsaddle`,
  vaultActivate = `vault.activate`,
  vaultAmbient = `vault.ambient`,
  vaultCloseShutter = `vault.close_shutter`,
  vaultDeactivate = `vault.deactivate`,
  vaultEjectItem = `vault.eject_item`,
  vaultInsertItem = `vault.insert_item`,
  vaultInsertItemFail = `vault.insert_item_fail`,
  vaultOpenShutter = `vault.open_shutter`,
  vaultRejectRewardedPlayer = `vault.reject_rewarded_player`,
  warn = `warn`,
  water = `water`,
  whine = `whine`,
  windChargeBurst = `wind_charge.burst`
}