/**
 * Plain-English descriptions for Minecraft Bedrock Edition components.
 * Used to provide tooltips in component editors so creators understand
 * what each component does without reading documentation.
 *
 * Coverage: ~200 components across entity behaviors, entity properties,
 * block components, and item components.
 */

export const componentDescriptions: Record<string, string> = {
  // ── Entity Behaviors ──────────────────────────────────────────────────

  "minecraft:behavior.random_stroll": "Makes this entity wander around randomly when idle",
  "minecraft:behavior.look_at_player": "Makes this entity look at nearby players",
  "minecraft:behavior.hurt_by_target": "Makes this entity attack whatever hurt it",
  "minecraft:behavior.nearest_attackable_target": "Makes this entity target the nearest valid enemy",
  "minecraft:behavior.melee_attack": "Makes this entity attack targets using melee (close range)",
  "minecraft:behavior.follow_parent": "Makes baby entities follow their parent",
  "minecraft:behavior.panic": "Makes this entity run away when hurt",
  "minecraft:behavior.tempt": "Makes this entity follow players holding certain items",
  "minecraft:behavior.breed": "Allows this entity to breed with others of its kind",
  "minecraft:behavior.float": "Makes this entity float on water instead of sinking",
  "minecraft:behavior.swim_idle": "Makes this entity swim around when in water",
  "minecraft:behavior.random_swim": "Makes this entity swim to random positions in water",
  "minecraft:behavior.avoid_mob_type": "Makes this entity run away from certain mob types",
  "minecraft:behavior.flee_sun": "Makes this entity seek shade during daytime",
  "minecraft:behavior.move_to_water": "Makes this entity seek out water",
  "minecraft:behavior.move_to_land": "Makes this entity seek out land when in water",
  "minecraft:behavior.eat_block": "Makes this entity eat blocks (like sheep eating grass)",
  "minecraft:behavior.lay_egg": "Makes this entity lay eggs",
  "minecraft:behavior.mount_pathing": "Enables this entity to find a path to something it wants to mount",
  "minecraft:behavior.open_door": "Allows this entity to open doors",
  "minecraft:behavior.ranged_attack": "Makes this entity use ranged attacks (projectiles)",
  "minecraft:behavior.stay_while_sitting": "Makes a tamed entity stay in place when told to sit",
  "minecraft:behavior.leap_at_target": "Makes this entity leap at its attack target",
  "minecraft:behavior.ocelot_sit_on_block": "Makes this entity sit on certain blocks (like cats)",
  "minecraft:behavior.pickup_items": "Makes this entity pick up items from the ground",
  "minecraft:behavior.player_ride_tamed": "Allows players to ride this tamed entity",
  "minecraft:behavior.scared": "Makes this entity display scared behavior",
  "minecraft:behavior.drop_item_for": "Makes this entity drop items for other entities",
  "minecraft:behavior.snacking": "Makes this entity eat items from its inventory",
  "minecraft:behavior.stomp_attack": "Makes this entity use a stomping attack",
  "minecraft:behavior.swoop_attack": "Makes this entity swoop down to attack targets",
  "minecraft:behavior.charge_attack": "Makes this entity charge at attack targets",
  "minecraft:behavior.circle_around_anchor": "Makes this entity fly in circles around a point",
  "minecraft:behavior.controlled_by_player": "Allows the player to control this entity while riding",
  "minecraft:behavior.defend_trusted_target": "Makes this entity defend entities it trusts",
  "minecraft:behavior.delayed_attack": "Makes this entity use attacks with a wind-up delay",
  "minecraft:behavior.door_interact": "Allows this entity to interact with doors",
  "minecraft:behavior.dragonchargeplayer": "Makes this dragon charge at players",
  "minecraft:behavior.enderman_leave_block": "Makes this enderman-like entity place blocks it's carrying",
  "minecraft:behavior.enderman_take_block": "Makes this enderman-like entity pick up blocks",
  "minecraft:behavior.explore_outskirts": "Makes this entity explore the edges of villages",
  "minecraft:behavior.find_cover": "Makes this entity find cover or shelter",
  "minecraft:behavior.find_mount": "Makes this entity find something to ride",
  "minecraft:behavior.find_underwater_treasure": "Makes this entity search for underwater treasure",
  "minecraft:behavior.go_home": "Makes this entity return to its home position",
  "minecraft:behavior.guardian_attack": "Makes this guardian-like entity use its laser attack",
  "minecraft:behavior.harvest_farm_block": "Makes this entity harvest crops from farm blocks",
  "minecraft:behavior.hide": "Makes this entity hide from threats",
  "minecraft:behavior.hold_ground": "Makes this entity stand its ground against attackers",
  "minecraft:behavior.inspect_bookshelf": "Makes this entity look at bookshelves",
  "minecraft:behavior.investigate_suspicious_location": "Makes this entity check out suspicious areas",
  "minecraft:behavior.jump_to_block": "Makes this entity jump to blocks (like goats)",
  "minecraft:behavior.knockback_roar": "Makes this entity roar and knock back nearby entities",
  "minecraft:behavior.lay_down": "Makes this entity lie down periodically",
  "minecraft:behavior.make_love": "Makes this villager-like entity breed",
  "minecraft:behavior.move_indoors": "Makes this entity move inside structures",
  "minecraft:behavior.move_through_village": "Makes this entity walk through villages",
  "minecraft:behavior.move_to_village": "Makes this entity seek out villages",
  "minecraft:behavior.nap": "Makes this entity take naps",
  "minecraft:behavior.pet_sleep_with_owner": "Makes this pet sleep near its owner",
  "minecraft:behavior.raid_garden": "Makes this entity eat crops from gardens",
  "minecraft:behavior.ram_attack": "Makes this entity charge and ram targets (like goats)",
  "minecraft:behavior.receive_love": "Makes this entity accept breeding from a partner",
  "minecraft:behavior.restrict_open_door": "Prevents this entity from going through open doors",
  "minecraft:behavior.rise_to_liquid_level": "Makes this entity rise to the surface of liquids",
  "minecraft:behavior.roll": "Makes this entity roll (like pandas)",
  "minecraft:behavior.run_around_like_crazy": "Makes this untamed entity run around wildly when mounted",
  "minecraft:behavior.send_event": "Triggers a game event under certain conditions",
  "minecraft:behavior.share_items": "Makes this entity share items with others",
  "minecraft:behavior.silverfish_merge_with_stone": "Makes this silverfish hide inside stone blocks",
  "minecraft:behavior.silverfish_wake_up_friends": "Makes this silverfish wake up other silverfish in blocks",
  "minecraft:behavior.skeleton_horse_trap": "Sets up the skeleton horse trap lightning event",
  "minecraft:behavior.sleep": "Makes this entity sleep in beds",
  "minecraft:behavior.sneeze": "Makes this entity sneeze (like baby pandas)",
  "minecraft:behavior.squid_dive": "Makes this squid dive deeper in water",
  "minecraft:behavior.squid_flee": "Makes this squid flee from threats by jetting away",
  "minecraft:behavior.squid_idle": "Makes this squid idle in water",
  "minecraft:behavior.squid_move_away_from_ground": "Makes this squid avoid the ocean floor",
  "minecraft:behavior.squid_out_of_water": "Makes this squid suffocate on land",
  "minecraft:behavior.stalk_and_pounce_on_target": "Makes this entity stalk then pounce on prey",
  "minecraft:behavior.stay_near_noteblock": "Makes this entity stay near active note blocks (like allays)",
  "minecraft:behavior.stomp_turtle_egg": "Makes this entity stomp on turtle eggs",
  "minecraft:behavior.stroll_towards_village": "Makes this entity walk toward villages",
  "minecraft:behavior.summon_entity": "Makes this entity summon other entities",
  "minecraft:behavior.swim_with_entity": "Makes this entity swim alongside other entities",
  "minecraft:behavior.swell": "Makes this creeper-like entity swell up before exploding",
  "minecraft:behavior.target_when_pushed": "Makes this entity target whatever pushed it",
  "minecraft:behavior.trade_interest": "Makes this entity show interest in trading",
  "minecraft:behavior.trade_with_player": "Allows this entity to trade with players",
  "minecraft:behavior.vex_copy_owner_target": "Makes this vex attack its owner's target",
  "minecraft:behavior.vex_random_move": "Makes this vex fly around randomly",
  "minecraft:behavior.wither_random_attack_pos_goal": "Makes this wither attack random positions",
  "minecraft:behavior.wither_target_highest_damage": "Makes this wither target whoever dealt most damage",
  "minecraft:behavior.work": "Makes this villager-like entity work at their job site",
  "minecraft:behavior.random_look_around": "Makes this entity look around randomly when idle",
  "minecraft:behavior.follow_mob": "Makes this entity follow other nearby mobs",
  "minecraft:behavior.random_fly": "Makes this entity fly to random positions",
  "minecraft:behavior.move_to_block": "Makes this entity move toward a specific block type",
  "minecraft:behavior.owner_hurt_by_target": "Makes this tamed entity target whatever hurt its owner",
  "minecraft:behavior.owner_hurt_target": "Makes this tamed entity target whatever its owner attacked",
  "minecraft:behavior.random_breach": "Makes this aquatic entity breach the water surface randomly",
  "minecraft:behavior.random_hover": "Makes this entity hover at random positions",
  "minecraft:behavior.random_sitting": "Makes this entity randomly sit down",
  "minecraft:behavior.look_at_entity": "Makes this entity look at nearby entities of a specific type",
  "minecraft:behavior.look_at_trading_player": "Makes this entity look at a player it's trading with",
  "minecraft:behavior.move_to_random_block": "Makes this entity move to a random block position",
  "minecraft:behavior.mingle": "Makes this villager-like entity gather and socialize with others",
  "minecraft:behavior.celebrate": "Makes this entity celebrate (like pillagers after a raid)",
  "minecraft:behavior.celebrate_survive": "Makes this villager celebrate surviving a raid",
  "minecraft:behavior.admire_item": "Makes this entity admire items it has picked up (like piglins)",
  "minecraft:behavior.barter": "Makes this entity barter items with players (like piglins)",
  "minecraft:behavior.equip_item": "Makes this entity equip items it picks up",
  "minecraft:behavior.follow_owner": "Makes this tamed entity follow its owner",
  "minecraft:behavior.random_look_around_and_sit": "Makes this entity randomly look around and sit",
  "minecraft:behavior.croak": "Makes this frog croak periodically",
  "minecraft:behavior.eat_mob": "Makes this entity eat other mobs (like frogs eating slimes)",
  "minecraft:behavior.lay_egg_at_location": "Makes this entity lay eggs at specific locations",
  "minecraft:behavior.sonic_boom": "Makes this entity use the Warden's sonic boom attack",
  "minecraft:behavior.dig": "Makes this entity dig into the ground (like the Warden)",
  "minecraft:behavior.emerge": "Makes this entity emerge from the ground (like the Warden)",
  "minecraft:behavior.roar": "Makes this entity roar (like the Warden)",
  "minecraft:behavior.sniff": "Makes this entity sniff to detect nearby entities (like the Warden)",
  "minecraft:behavior.timer_flag_1": "Sets a timed flag for triggering events",
  "minecraft:behavior.timer_flag_2": "Sets a second timed flag for triggering events",
  "minecraft:behavior.timer_flag_3": "Sets a third timed flag for triggering events",

  // ── Entity Properties / Attributes ────────────────────────────────────

  "minecraft:physics": "Enables gravity and collision physics for this entity",
  "minecraft:collision_box": "Defines the size of the entity's hitbox",
  "minecraft:health": "Sets how many health points (HP) this entity has",
  "minecraft:movement": "Sets the entity's base movement speed",
  "minecraft:movement.basic": "Uses basic ground-based movement",
  "minecraft:movement.amphibious": "Allows movement on both land and water",
  "minecraft:movement.fly": "Enables flying movement",
  "minecraft:movement.hover": "Enables hovering flight movement",
  "minecraft:movement.skip": "Uses skipping movement (like rabbits)",
  "minecraft:movement.sway": "Uses swaying movement (like fish)",
  "minecraft:movement.swim": "Uses swimming movement in water",
  "minecraft:movement.glide": "Uses gliding movement (like phantom)",
  "minecraft:movement.jump": "Uses jumping movement",
  "minecraft:navigation.walk": "Navigates by walking on land, avoiding dangerous blocks",
  "minecraft:navigation.climb": "Navigates by climbing surfaces",
  "minecraft:navigation.float": "Navigates by floating on water",
  "minecraft:navigation.fly": "Navigates by flying through the air",
  "minecraft:navigation.swim": "Navigates by swimming through water",
  "minecraft:navigation.hover": "Navigates by hovering above the ground",
  "minecraft:navigation.generic": "Uses generic pathfinding navigation",
  "minecraft:attack": "Defines this entity's melee attack damage",
  "minecraft:follow_range": "How far this entity can detect and follow targets",
  "minecraft:knockback_resistance": "How resistant this entity is to being knocked back",
  "minecraft:loot": "What items this entity drops when killed",
  "minecraft:equipment": "What items this entity spawns wearing or holding",
  "minecraft:type_family": "What kind of creature this is (e.g., 'monster', 'animal', 'mob')",
  "minecraft:breathable": "Controls breathing — whether entity breathes air, water, or lava",
  "minecraft:nameable": "Allows this entity to be named with a name tag",
  "minecraft:rideable": "Allows players or other entities to ride this entity",
  "minecraft:is_baby": "Marks this entity as a baby variant",
  "minecraft:is_tamed": "Marks this entity as tamed",
  "minecraft:ageable": "Allows this entity to age from baby to adult",
  "minecraft:breedable": "Allows this entity to be bred using specific items",
  "minecraft:tameable": "Allows this entity to be tamed by players",
  "minecraft:leashable": "Allows this entity to be attached to a lead",
  "minecraft:healable": "Allows this entity to be healed using specific items",
  "minecraft:experience_reward": "How much XP this entity drops when killed",
  "minecraft:despawn": "Controls when this entity despawns (disappears) from the world",
  "minecraft:spawn_entity": "Makes this entity periodically spawn other entities",
  "minecraft:projectile": "Makes this entity behave as a projectile (like arrows)",
  "minecraft:explode": "Makes this entity explode under certain conditions",
  "minecraft:damage_sensor": "Defines how this entity reacts to different types of damage",
  "minecraft:environment_sensor": "Triggers events based on environmental conditions",
  "minecraft:on_target_acquired": "Event triggered when this entity finds a target",
  "minecraft:on_target_escape": "Event triggered when this entity loses its target",
  "minecraft:is_sheared": "Marks this entity as having been sheared",
  "minecraft:is_saddled": "Marks this entity as wearing a saddle",
  "minecraft:is_chested": "Marks this entity as wearing a chest",
  "minecraft:scale": "Sets the visual scale (size) of this entity",
  "minecraft:can_climb": "Allows this entity to climb ladders and vines",
  "minecraft:can_fly": "Allows this entity to fly",
  "minecraft:can_power_jump": "Allows this entity to power jump (like horses)",
  "minecraft:fire_immune": "Makes this entity immune to fire damage",
  "minecraft:floats_in_liquid": "Makes this entity float on liquids",
  "minecraft:pushable": "Controls whether this entity can be pushed by other entities",
  "minecraft:underwater_movement": "Sets how fast this entity moves in water",
  "minecraft:water_movement": "Controls the entity's water drag factor",
  "minecraft:burns_in_daylight": "Makes this entity take damage from sunlight",
  "minecraft:skin_id": "Sets which skin variant this entity uses",
  "minecraft:variant": "Sets which visual variant this entity uses",
  "minecraft:mark_variant": "Sets an additional visual variant marker",
  "minecraft:color": "Sets the color of this entity (like sheep wool color)",
  "minecraft:color2": "Sets a secondary color for this entity",
  "minecraft:is_illager_captain": "Marks this entity as a raid captain",
  "minecraft:is_stunned": "Marks this entity as stunned",
  "minecraft:is_charged": "Marks this entity as charged (like charged creepers)",
  "minecraft:is_ignited": "Marks this entity as on fire or ignited",
  "minecraft:hurt_on_condition": "Makes this entity take damage under certain conditions",
  "minecraft:conditional_bandwidth_optimization": "Optimizes network data based on conditions",
  "minecraft:strength": "Sets the strength level of this entity",
  "minecraft:instant_despawn": "Makes this entity despawn immediately when out of range",
  "minecraft:persistent": "Prevents this entity from despawning naturally",
  "minecraft:target_nearby_sensor": "Detects when other entities are nearby",
  "minecraft:teleport": "Allows this entity to teleport (like endermen)",
  "minecraft:shooter": "Defines projectile shooting properties",
  "minecraft:transformation": "Defines how this entity transforms into another entity",
  "minecraft:mob_effect": "Applies status effects to nearby entities",
  "minecraft:area_attack": "Damages all entities within a radius",
  "minecraft:spell_effects": "Applies spell-like effects",
  "minecraft:angry": "Controls the entity's anger state and duration",
  "minecraft:annotation.break_door": "Marks this entity as being able to break doors",
  "minecraft:annotation.open_door": "Marks this entity as being able to open doors",
  "minecraft:balloonable": "Allows a balloon to be attached to this entity",
  "minecraft:boss": "Makes this entity display a boss health bar",
  "minecraft:break_blocks": "Allows this entity to break blocks as it moves",
  "minecraft:custom_hit_test": "Defines a custom hit area for this entity",
  "minecraft:damage_over_time": "Applies continuous damage to this entity over time",
  "minecraft:dash": "Allows this entity to dash forward (like camels)",
  "minecraft:economy_trade_table": "Defines this entity's trading table and economy",
  "minecraft:entity_sensor": "Detects entities within a specified area",
  "minecraft:game_event_movement_tracking": "Tracks entity movement for sculk sensors",
  "minecraft:genetics": "Defines genetic traits for breeding and inheritance",
  "minecraft:giveable": "Allows items to be given to this entity",
  "minecraft:ground_offset": "Offsets this entity above the ground",
  "minecraft:group_size": "Defines group size bonuses for this entity",
  "minecraft:home": "Defines a home position this entity remembers",
  "minecraft:horse.jump_strength": "Sets this horse-like entity's jump strength",
  "minecraft:input_ground_controlled": "Makes this entity controlled by rider input on the ground",
  "minecraft:inside_block_notifier": "Triggers events when this entity is inside certain blocks",
  "minecraft:interact": "Defines interactions players can have with this entity",
  "minecraft:inventory": "Gives this entity an inventory container",
  "minecraft:jump.dynamic": "Uses dynamic jump height based on speed",
  "minecraft:jump.static": "Uses a fixed jump height",
  "minecraft:lava_movement": "Sets how fast this entity moves in lava",
  "minecraft:lookat": "Triggers events when a player looks at this entity",
  "minecraft:managed_wandering_trader": "Makes this entity behave as a wandering trader",
  "minecraft:movement_sound_distance_offset": "Offsets the distance for movement sounds",
  "minecraft:npc": "Makes this entity function as an NPC",
  "minecraft:out_of_control": "Marks this entity as out of the rider's control",
  "minecraft:peek": "Allows this entity to peek (like shulkers)",
  "minecraft:preferred_path": "Defines preferred block types for pathfinding",
  "minecraft:rail_movement": "Allows this entity to move along rails",
  "minecraft:rail_sensor": "Triggers events when this entity is on rails",
  "minecraft:ravager_blocked": "Handles ravager stun behavior when blocked",
  "minecraft:shareable": "Defines items this entity wants to pick up and share",
  "minecraft:sittable": "Allows this entity to sit on command",
  "minecraft:trade_table": "Defines this entity's trading table",
  "minecraft:trail": "Leaves a trail of particles or blocks behind this entity",
  "minecraft:trust": "Controls the trust system for this entity",
  "minecraft:trusting": "Allows this entity to build trust with players",
  "minecraft:vibration_damper": "Prevents this entity from triggering sculk sensors",
  "minecraft:vibration_listener": "Makes this entity listen for vibrations (like the Warden)",
  "minecraft:variable_max_auto_step": "Controls auto-step height based on conditions",

  // ── Block Components ──────────────────────────────────────────────────

  "minecraft:destructible_by_mining": "Controls whether and how fast this block can be mined",
  "minecraft:destructible_by_explosion": "Controls whether this block can be destroyed by explosions",
  "minecraft:block_light_emission": "How much light this block emits (0.0–1.0)",
  "minecraft:block_light_absorption": "How much light this block absorbs",
  "minecraft:destroy_time": "How long it takes to mine this block",
  "minecraft:explosion_resistance": "How resistant this block is to explosions",
  "minecraft:friction": "How slippery this block's surface is (0.0–1.0)",
  "minecraft:flammable": "Whether and how easily this block catches fire",
  "minecraft:geometry": "Custom 3D shape for this block",
  "minecraft:material_instances": "Textures and rendering settings for each face",
  "minecraft:selection_box": "The selection outline shape of this block",
  "minecraft:placement_filter": "Rules for where this block can be placed",
  "minecraft:crafting_table": "Makes this block function as a crafting table",
  "minecraft:display_name": "The name shown for this block in-game",
  "minecraft:unit_cube": "Makes this block render as a standard full cube",
  "minecraft:map_color": "The color shown on maps for this block",
  "minecraft:block_light_filter": "How much this block filters light passing through",
  "minecraft:light_emission": "How much light this block emits (0–15)",
  "minecraft:light_dampening": "How much this block dampens light (0–15)",
  "minecraft:block_transformation": "Applies rotation, scale, or translation to this block's geometry",
  "minecraft:bone_visibility": "Controls which bones are visible in this block's geometry",
  "minecraft:item_visual": "Controls how this block appears as an item",
  "minecraft:block_collision_box": "The collision shape of this block",
  "minecraft:tick": "Makes this block receive scheduled tick updates",
  "minecraft:queued_ticking": "Makes this block receive queued tick updates",
  "minecraft:random_ticking": "Makes this block receive random tick updates (like crops)",
  "minecraft:on_interact": "Event triggered when a player interacts with this block",
  "minecraft:on_placed": "Event triggered when this block is placed",
  "minecraft:on_player_destroyed": "Event triggered when a player destroys this block",
  "minecraft:on_player_placing": "Event triggered when a player is placing this block",
  "minecraft:on_step_on": "Event triggered when an entity steps on this block",
  "minecraft:on_step_off": "Event triggered when an entity steps off this block",
  "minecraft:on_fall_on": "Event triggered when an entity falls on this block",
  "minecraft:entity_fall_on": "Controls damage to entities that fall on this block",
  "minecraft:redstone_conductivity": "Controls how this block conducts redstone signals",
  "minecraft:custom_components": "Lists custom script components attached to this block",

  // ── Item Components ───────────────────────────────────────────────────

  "minecraft:icon": "The inventory icon for this item",
  "minecraft:max_stack_size": "Maximum number that can stack in one slot",
  "minecraft:hand_equipped": "Whether this item shows in the entity's hand when held",
  "minecraft:use_duration": "How long it takes to use this item (in seconds)",
  "minecraft:food": "Makes this item edible with nutrition and saturation values",
  "minecraft:throwable": "Makes this item throwable like a snowball",
  "minecraft:weapon": "Makes this item function as a weapon with damage",
  "minecraft:armor": "Makes this item function as armor with protection",
  "minecraft:durability": "Gives this item a durability that decreases with use",
  "minecraft:cooldown": "Adds a cooldown timer after using this item",
  "minecraft:wearable": "Makes this item wearable in an armor slot",
  "minecraft:item_display_name": "The name shown for this item in-game",
  "minecraft:allow_off_hand": "Whether this item can be held in the off-hand",
  "minecraft:creative_category": "Which creative inventory tab this item appears in",
  "minecraft:damage": "Damage dealt by this item",
  "minecraft:enchantable": "Whether and how this item can be enchanted",
  "minecraft:repairable": "Whether and how this item can be repaired",
  "minecraft:record": "Makes this item function as a music disc",
  "minecraft:entity_placer": "Makes this item place an entity when used (like spawn eggs)",
  "minecraft:block_placer": "Makes this item place a block when used",
  "minecraft:render_offsets": "Adjusts how this item renders in hand",
  "minecraft:glint": "Adds an enchanted glint effect to this item",
  "minecraft:hover_text_color": "Sets the color of this item's hover text",
  "minecraft:interact_button": "Shows an interact button when targeting an entity",
  "minecraft:liquid_clipped": "Controls whether this item is clipped by liquids",
  "minecraft:mining_speed": "Sets how fast this item mines blocks",
  "minecraft:rarity": "Sets the rarity display color for this item name",
  "minecraft:seed": "Makes this item plantable as a seed on farmland",
  "minecraft:stacked_by_data": "Determines whether items with different data values stack",
  "minecraft:tags": "Tags for this item used in recipes and filters",
  "minecraft:use_animation": "Which animation plays when using this item (eat, drink, bow, etc.)",
  "minecraft:use_modifiers": "Modifiers applied during item use (movement speed, etc.)",
  "minecraft:digger": "Defines which blocks this tool can mine and at what speed",
  "minecraft:dyeable": "Makes this item dyeable with different colors",
  "minecraft:bundle_interaction": "Makes this item behave as a bundle container",
  "minecraft:can_destroy_in_creative": "Whether this item can destroy blocks in creative mode",
  "minecraft:item_custom_components": "Lists custom script components attached to this item",
};

/**
 * Gets a plain-English description for a Minecraft component ID.
 * @param componentId The full or short component ID (e.g., "minecraft:physics" or "physics")
 * @returns The description string, or undefined if not found
 */
export function getComponentDescription(componentId: string): string | undefined {
  if (componentDescriptions[componentId]) {
    return componentDescriptions[componentId];
  }

  // Try with minecraft: prefix
  if (!componentId.startsWith("minecraft:")) {
    const withPrefix = "minecraft:" + componentId;
    if (componentDescriptions[withPrefix]) {
      return componentDescriptions[withPrefix];
    }
  }

  return undefined;
}
