// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

/**
 * ItemSpriteIcon - Renders a Minecraft item as a pixelated sprite in a slot frame.
 *
 * When a sprite atlas is available (generated by scripts/generate-item-catalog.mjs),
 * renders via CSS background-position on the single atlas PNG — no individual HTTP
 * requests needed. Falls back to individual <img> tags when atlas data is absent.
 *
 * Used in recipe editors, crafting grids, item pickers, and loot table editors.
 */

import React, { Component } from "react";
import "./ItemSpriteIcon.css";
import Utilities from "../../../core/Utilities";
import CreatorToolsHost from "../../../app/CreatorToolsHost";
import ItemSpriteDatabase from "./ItemSpriteDatabase";
import { resolveLegacyItem } from "../../../minecraft/LegacyItemMap";

export type ItemSpriteSize = "small" | "medium" | "large";

export interface IItemSpriteIconProps {
  itemId?: string;
  /** Optional Bedrock pre-flattening data value. When provided alongside a
   * legacy item id (e.g. `minecraft:planks` + data 4), the icon resolves to
   * the modern flattened id (`minecraft:acacia_planks`) so the right sprite
   * is shown instead of the 4-letter placeholder. */
  data?: number;
  /** Pre-resolved sprite filename from the static catalog (e.g. "apple.png"). When provided, used instead of guessing from itemId. */
  spriteFilename?: string | null;
  /** Atlas X pixel offset (from catalog). When set alongside atlasY, renders from the atlas. */
  atlasX?: number;
  /** Atlas Y pixel offset (from catalog). */
  atlasY?: number;
  size?: ItemSpriteSize;
  darkTheme?: boolean;
  title?: string;
  onClick?: () => void;
  className?: string;
  empty?: boolean;
}

interface IItemSpriteIconState {
  imageError: boolean;
  /** Bumped after an async catalog load resolves so we re-render with looked-up sprite/atlas info. */
  catalogTick: number;
}

export default class ItemSpriteIcon extends Component<IItemSpriteIconProps, IItemSpriteIconState> {
  private _isMounted = false;

  constructor(props: IItemSpriteIconProps) {
    super(props);
    this.state = { imageError: false, catalogTick: 0 };
    this._handleImageError = this._handleImageError.bind(this);
  }

  componentDidMount(): void {
    this._isMounted = true;
    this._maybeLoadCatalog();
  }

  componentWillUnmount(): void {
    this._isMounted = false;
  }

  componentDidUpdate(prevProps: IItemSpriteIconProps): void {
    if (prevProps.itemId !== this.props.itemId) {
      this.setState({ imageError: false });
      this._maybeLoadCatalog();
    }
  }

  /**
   * If the caller only gave us an itemId (no pre-resolved spriteFilename or
   * atlas coords) and the vanilla catalog hasn't loaded yet, kick off a load
   * so the next render can pull atlas coords for a proper sprite. Without
   * this the icon falls back to the 4-letter placeholder forever.
   */
  private _maybeLoadCatalog(): void {
    if (!this.props.itemId) return;
    if (this.props.atlasX !== undefined && this.props.atlasY !== undefined) return;
    if (this.props.spriteFilename !== undefined) return;
    if (ItemSpriteDatabase.getEntrySync(this.props.itemId) !== undefined) return;

    ItemSpriteDatabase.ensureLoaded().then(() => {
      if (this._isMounted) {
        this.setState((s) => ({ catalogTick: s.catalogTick + 1 }));
      }
    });
  }

  private _handleImageError(): void {
    this.setState({ imageError: true });
  }

  static getCleanItemName(itemId: string): string {
    let name = itemId;
    if (name.includes(":")) {
      name = name.substring(name.indexOf(":") + 1);
    }
    return name;
  }

  /**
   * Minecraft ids and texture filenames are restricted to lowercase letters,
   * digits, underscore, dot, dash, and colon. Anything else could allow path
   * traversal or scheme injection when concatenated into a URL, so we reject
   * those values. (CodeQL js/xss-through-dom flagged the <img src={…}> sink
   * because itemId/spriteFilename originate from project JSON that a creator
   * could edit by hand.)
   */
  private static readonly SAFE_SEGMENT_RE = /^[a-zA-Z0-9_.:\-]+$/;

  private static isSafeSegment(value: string): boolean {
    return value.length > 0 && value.length < 256 && ItemSpriteIcon.SAFE_SEGMENT_RE.test(value);
  }

  static getItemSpriteUrl(itemId: string, spriteFilename?: string | null): string | null {
    if (spriteFilename) {
      // "b:" prefix means the sprite is in the blocks/ directory
      if (spriteFilename.startsWith("b:")) {
        const rest = spriteFilename.substring(2);
        if (!ItemSpriteIcon.isSafeSegment(rest)) return null;
        return (
          CreatorToolsHost.contentWebRoot +
          "res/latest/van/serve/resource_pack/textures/blocks/" +
          encodeURIComponent(rest)
        );
      }
      if (!ItemSpriteIcon.isSafeSegment(spriteFilename)) return null;
      return (
        CreatorToolsHost.contentWebRoot +
        "res/latest/van/serve/resource_pack/textures/items/" +
        encodeURIComponent(spriteFilename)
      );
    }
    const cleanName = ItemSpriteIcon.getCleanItemName(itemId);
    if (!ItemSpriteIcon.isSafeSegment(cleanName)) return null;
    return (
      CreatorToolsHost.contentWebRoot +
      "res/latest/van/serve/resource_pack/textures/items/" +
      encodeURIComponent(cleanName) +
      ".png"
    );
  }

  static getDisplayName(itemId: string): string {
    const cleanName = ItemSpriteIcon.getCleanItemName(itemId);
    return Utilities.humanifyMinecraftName(cleanName);
  }

  private static readonly SIZE_PX: Record<ItemSpriteSize, number> = {
    small: 28,
    medium: 44,
    large: 60,
  };

  render() {
    const size = this.props.size || "medium";
    const isEmpty = this.props.empty || !this.props.itemId;
    const isDark = this.props.darkTheme;

    if (isEmpty) {
      return (
        <div className={"rcisi-container " + (this.props.className || "")}>
          <div
            className={"rcisi-slot rcisi-empty rcisi-slot-" + size + (isDark ? " rcisi-empty-dark" : "")}
            onClick={this.props.onClick}
            title={this.props.title || "Empty slot"}
          />
        </div>
      );
    }

    const rawItemId = this.props.itemId!;
    // Resolve legacy (pre-flattening) ids like `minecraft:planks` + data 4 to
    // their modern flattened equivalent (`minecraft:acacia_planks`) so the
    // catalog/atlas lookup can find a real sprite. Falls back to the raw id
    // when nothing matches, preserving custom-namespaced items untouched.
    const itemId = resolveLegacyItem(rawItemId, this.props.data) || rawItemId;
    const displayName = this.props.title || ItemSpriteIcon.getDisplayName(itemId);
    const slotClass = "rcisi-slot rcisi-slot-" + size + (isDark ? " rcisi-slot-dark" : "");

    // If the caller didn't pre-resolve atlas coords or sprite filename, fall
    // back to a sync catalog lookup. This lets simple call sites
    // (`<ItemSpriteIcon itemId="minecraft:apple" />`) still show real art.
    let resolvedAtlasX = this.props.atlasX;
    let resolvedAtlasY = this.props.atlasY;
    let resolvedSpriteFilename = this.props.spriteFilename;
    if ((resolvedAtlasX === undefined || resolvedAtlasY === undefined) && resolvedSpriteFilename === undefined) {
      const entry = ItemSpriteDatabase.getEntrySync(itemId);
      if (entry) {
        resolvedAtlasX = entry.atlasX;
        resolvedAtlasY = entry.atlasY;
        resolvedSpriteFilename = entry.sprite;
      }
    }

    // Atlas path: render via CSS background-position on the single atlas PNG.
    // Element is sized at the source sprite size (16×16), positioned at the
    // natural atlas coordinates, then CSS-scaled up to the display size.
    // The parent .rcisi-slot has overflow:hidden so only one cell is visible.
    const useAtlas = ItemSpriteDatabase.hasAtlas && resolvedAtlasX !== undefined && resolvedAtlasY !== undefined;
    if (useAtlas) {
      const atlasUrl = ItemSpriteDatabase.atlasUrl!;
      const srcSize = ItemSpriteDatabase.atlasSpriteSize;
      const displaySize = ItemSpriteIcon.SIZE_PX[size] - 2; // subtract 1px border each side
      const scale = displaySize / srcSize;

      const style: React.CSSProperties = {
        backgroundImage: `url(${atlasUrl})`,
        backgroundPosition: `-${resolvedAtlasX! * scale}px -${resolvedAtlasY! * scale}px`,
        backgroundSize: `${ItemSpriteDatabase.atlasWidth * scale}px ${ItemSpriteDatabase.atlasHeight * scale}px`,
        width: displaySize,
        height: displaySize,
        imageRendering: "pixelated",
      };

      return (
        <div className={"rcisi-container " + (this.props.className || "")}>
          <div className={slotClass} onClick={this.props.onClick} title={displayName}>
            <div className="rcisi-atlas-sprite" style={style} />
          </div>
        </div>
      );
    }

    // Fallback: individual image request
    const spriteUrl = ItemSpriteIcon.getItemSpriteUrl(itemId, resolvedSpriteFilename);
    const hasKnownSprite = resolvedSpriteFilename !== null;

    return (
      <div className={"rcisi-container " + (this.props.className || "")}>
        <div className={slotClass} onClick={this.props.onClick} title={displayName}>
          {hasKnownSprite && !this.state.imageError && spriteUrl ? (
            <img
              className="rcisi-image"
              src={spriteUrl}
              alt={displayName}
              decoding="async"
              onError={this._handleImageError}
              draggable={false}
            />
          ) : (
            <div className="rcisi-fallback">{ItemSpriteIcon.getCleanItemName(itemId).substring(0, 4)}</div>
          )}
        </div>
      </div>
    );
  }
}
