const path = require("path");

module.exports = {
  packagerConfig: {
    icon: "./res/icons/icon",
    name: "mctools",
    prune: true,
    junk: true,
    asar: false,
    win32metadata: {
      CompanyName: "Mojang",
      ProductName: "Minecraft Creator Tools",
    },
    ignore: [
      "\\.scss$",
      "^/app",
      "^/docs",
      "^/make",
      "^/tools",
      "^/out",
      "^/toolbuild/blb",
      "^/toolbuild/vsc",
      "^/node_modules_overrides",
      "^/node_modules_archive",
      "^/jsnode",
      "^/public_supplemental",
      "^/index.html",
      "^/public/",
      "^/tsconfig",
      "^/forge.config.js",
      "^/playwright",
      "^/creatortools.forge.",
      "^/vite.config.",
      "^/gulpfile.js",
      "^/webpack",
      "^/reslist",
      "^/debugoutput",
      "^/public",
      "^/res",
      "^/scripts",
      "^/scriptlibs",
      "^/site",
      "^/vscode",
      "^/electron-build",
      "^/animation_controllers",
      "^/render_controllers",
      "^/node_modules/.cache",
      "^/node_modules/internal",
      "^/node_modules/fork-ts-checker-webpack-plugin",
      "^/node_modules/optimize-css-assets-webpack-plugin",
      "^/node_modules/monaco-editor-webpack-plugin",
      "^/node_modules/terser-webpack-plugin",
      "^/node_modules/html-webpack-plugin",
      "^/node_modules/@babel/plugin-",
      "^(/node_modules/babel/@babel/plugin-)",
      "^/node_modules/@babel/preset-",
      "^(/node_modules/babel/@babel/preset-)",
      "^/node_modules/babylonjs.*",
      "^/node_modules/browserify.*",
      "^/node_modules/d3-.*",
      "^/node_modules/tui-.*",
      "^/node_modules/react-.*",
      "^/node_modules/css-.*",
      "^/node_modules/@bcoe",
      "^/node_modules/@rushstack.*",
      "^/node_modules/@playwright.*",
      "^/node_modules/@toast-ui.*",
      "^/node_modules/@xyflow.*",
      "^/node_modules/@vite.*",
      "^/node_modules/@fluentui.*",
      "^/node_modules/@types",
      "^/node_modules/@uifabric",
      "^/node_modules/parallel-transform",
      "^/node_modules/fluent-ui",
      "^/node_modules/language-subtag-registry",
      "^/node_modules/@monaco",
      "^/node_modules/@gulp-sourcemaps",
      "^/node_modules/@minecraft",
      "^/node_modules/@webpack-cli",
      "^/node_modules/@npmcli",
      "^/node_modules/@tsconfig",
      "^/node_modules/cssdb",
      "^/node_modules/css-in-js-utils",
      "^/node_modules/postcss",
      "^/node_modules/browser",
      "^/node_modules/workbox",
      "^/node_modules/font-awesome",
      "^/node_modules/file-saver",
      "^/node_modules/@vscode",
      "^/node_modules/@surma",
      "^/node_modules/@csstools",
      "^/node_modules/@istanbuljs",
      "^/node_modules/@jest",
      "^/node_modules/@fortawesome",
      "^/node_modules/@webassemblyjs",
      "^/node_modules/@testing-library",
      "^/node_modules/babel",
      "^/node_modules/bcrypt-pbkdf",
      "^/node_modules/cssnano",
      "^/node_modules/fela",
      "^/node_modules/jest",
      "^/node_modules/sprintf-js",
      "^/node_modules/decimal.js",
      "^/node_modules/he",
      "^/node_modules/jsdom",
      "^/node_modules/flatted",
      "^/node_modules/serve-index",
      "^/node_modules/monaco-editor",
      "^/node_modules/postcss",
      "^/node_modules/resolve-url-loader",
      "^/node_modules/vm-browserify",
      "^/node_modules/webpack",
      "^/node_modules/workbox",
      "^/node_modules/istanbul",
      "^/node_modules/leaflet",
      "^/node_modules/public-encrypt",
      "^/node_modules/font-awesome",
      "^/node_modules/typescript",
      "^/node_modules/base64-js",
      "^/src",
      "^/ui",
      "^/jsmin",
      "^/.github",
      "^/libnode",
      "^/fogs",
      "^/build/min-maps",
      "^/public/data",
      "^/public/dist",
      "^/public/min-maps",
      "^/public/res",
      "^/particles",
      "^/build/res/latest/van/preview/resource_pack/textures/ui/",
      "^/build/res/latest/van/release/resource_pack/textures/ui/",
      "^/test",
      "^/.vscode",
      "source-map",
      "^/tools/(?!electron)",
      "^/tools/electron/package-electron.js",
      "runner\\.html$",
      "tslib\\.html$",
      "tslib\\.es6\\.html$",
      "Makefile$",
      "node-which$",
      "publish-built-version$",
      "travis-gh-pages$",
      "uuid$",
      "macos-trash$",
      "\\.exe$",
      "\\.ts$",
      "\\.cmd$",
      "\\.pptx$",
      "\\.docx$",
      "\\.xlsx$",
      "\\.ppt$",
      "\\.pst$",
      "\\.ost$",
      "\\.def$",
      "\\.cs$",
      "\\.msg$",
      "\\.doc$",
      "\\.xls$",
      "\\.jst$",
      "\\.iml$",
      "\\.ai$",
      "\\.xclangspec$",
      "\\.pbfilespec$",
      "\\.lintstagedrc$",
      "\\.babelrc$",
      "\\.huskyrc$",
      "\\.gyp$",
      "\\.gypi$",
      "\\.gitattributes$",
      "\\.fontified$",
      "\\.nvmrc$",
      "\\.opts$",
      "\\.nix$",
      "\\.lock$",
      "\\.patch$",
      "\\.flake8$",
      "\\.wmf$",
      "\\.sh$",
      "\\.bat$",
      "\\.yaml$",
      "\\.py$",
      "\\.pyc$",
      "\\.bin$",
      "\\.bak$",
      "\\.bnf$",
      "\\.closure-compiler$",
      "\\.webmanifest$",
      "\\.ps1$",
      "\\.pfx$",
      "\\.cer$",
      "nodejs.json",
      "\\.xml$",
      "\\.lint$",
      "usage.txt",
      "\\.gitattributes.txt$",
      "stdout.txt",
      "stderr.txt",
      "config-overrides.js",
      "changes.html",
      "manual-test.html",
      "example.html",
      "manual-test.html",
      "test-qunit.html",
      "\\.eslintrc$",
      "\\.eslintrc.json$",
      "\\.jscrc$",
      "\\.jscsrc$",
      "\\.pdf$",
      "\\.coffee$",
      "\\.stub$",
      "\\.swf$",
      "\\.map$",
      "\\.less$",
      "\\.prettierrc.json$",
      "robots.txt$",
      "site.manifest$",
      "/public/manifest.json$",
      "\\.yml$",
      "\\.testignore$",
      "\\.jscs.json$",
      "\\.jsfmtrc$",
      "\\.jshintrc$",
      "\\.nycrc$",
      "\\.jshintignore$",
      "\\.tm_properties$",
      "\\.npmignore$",
      "\\.eslintignore$",
      "\\.gitkeep$",
      "\\.eslintcache$",
      "\\.editorconfig$",
      "\\.markdown$",
      "\\.flow$",
      "^/(.babelrc|robots.txt|source-map-generator.js|.d.ts|.eslintrc|tsconfig.json|.gitignore|.npmrc|kill-nslog|README)",
    ],
  },
  makers: [
    {
      name: "@electron-forge/maker-squirrel",
      config: {
        name: "mctools",
        title: "Minecraft Creator Tools",
        authors: "Mojang",
        owners: "Minecraft Creator Tools",
        copyright: "Copyright (c) 2026 Mojang AB",
        setupIcon: path.join(__dirname, "/res/icons/icon.ico"),
        loadingGif: path.join(__dirname, "/res/mctoolsloading.gif"),
        description: "Tools for developers and creators for working with Minecraft Bedrock Edition.",
      },
    },
    {
      name: "@electron-forge/maker-zip",
    },
  ],
  buildIdentifier: "mctools-build",
};
