import IGitHubInfo from "./IGitHubInfo";

export const MaxItemTypes = 88;

export enum ProjectItemType {
  unknown = 0,
  testJs = 1,
  js = 2,
  catalogIndexJs = 3,
  structure = 4,
  behaviorPackManifestJson = 5,
  json = 6,
  MCWorld = 7,
  MCTemplate = 8,
  MCFunction = 9,
  entityTypeBehaviorJson = 10,
  entityTypeBaseJs = 11,
  autoScriptJson = 12,
  ts = 13,
  resourcePackManifestJson = 14,
  worldTest = 15,
  worldFolder = 16,
  behaviorPackListJson = 17,
  resourcePackListJson = 18,
  animationBehaviorJson = 19,
  animationControllerBehaviorJson = 20,
  blockTypeBehaviorJson = 21,
  blockMaterialsBehaviorJson = 22,
  itemTypeBehaviorJson = 23,
  lootTableBehaviorJson = 24,
  biomeResourceJson = 25,
  blocksCatalogResourceJson = 26,
  soundsCatalogResourceJson = 27,
  animationResourceJson = 28,
  animationControllerResourceJson = 29,
  entityTypeResourceJson = 30,
  fogResourceJson = 31,
  modelJson = 32,
  particleJson = 33,
  renderControllerJson = 34,
  itemTextureJson = 35,
  uiJson = 36,
  languagesCatalogResourceJson = 37,
  biomeBehaviorJson = 38,
  dialogueBehaviorJson = 39,
  featureRuleBehaviorJson = 40,
  featureBehaviorJson = 41,
  functionEventJson = 42,
  recipeBehaviorJson = 43,
  spawnRuleBehaviorJson = 44,
  tradingBehaviorJson = 45,
  volumeBehaviorJson = 46,
  attachableResourceJson = 47,
  itemTypeResourceJson = 48,
  materialsResourceJson = 49,
  musicDefinitionJson = 50,
  soundDefinitionJson = 51,
  blockTypeResourceJson = 52,
  MCAddon = 53,
  zip = 54,
  MCPack = 55,
  documentedType = 56,
  documentedCommand = 57,
  tsconfigJson = 58,
  packageJson = 59,
  packageLockJson = 60,
  docInfoJson = 61,
  typesDefinitionJson = 62,
  commandSetDefinitionJson = 63,
  jsconfigJson = 64,
  docfxJson = 65,
  jsdocJson = 66,
  skinPackManifestJson = 67,
  worldTemplateManifestJson = 68,
  buildProcessedJs = 69,
  entityTypeBaseTs = 70,
  blockTypeBaseJs = 71,
  blockTypeBaseTs = 72,
  MCProject = 73,
  image = 74,
  vsCodeLaunchJson = 75,
  vsCodeTasksJson = 76,
  vsCodeSettingsJson = 77,
  vsCodeExtensionsJson = 78,
  lang = 79,
  projectSummaryMetadata = 80,
  tickJson = 81,
  cameraJson = 82,
  material = 83,
  materialSetJson = 84,
  vertex = 85,
  fragment = 86,
  geometry = 87,
}

export enum ProjectItemStorageType {
  singleFile = 0,
  folder = 1,
}

export enum ProjectItemEditPreference {
  projectDefault = 0,
  forceEditor = 1,
  forceRaw = 2,
}

export enum ProjectItemErrorStatus {
  none = 0,
  unprocessable = 1,
}

export default interface IProjectItemData {
  itemType: ProjectItemType;
  storagePath: string | null | undefined;
  tags: string[];
  name: string;
  storageType: ProjectItemStorageType | undefined;
  gitHubReference?: IGitHubInfo;
  isAutogenerated?: boolean;
  editPreference?: ProjectItemEditPreference;
  errorMessage?: string;
  errorStatus?: ProjectItemErrorStatus;
  items?: IProjectItemData[];
}
